# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Topic

# Model Form Field configuration
form: @/plugins/rainlab/forum/models/topic/fields.yaml

# Model Class name
modelClass: RainLab\Forum\Models\Topic

# Default redirect location
defaultRedirect: rainlab/forum/topics

# Create page
create:
    title: Create Topics
    redirect: rainlab/forum/topics/update/:id
    redirectClose: rainlab/forum/topics

# Update page
update:
    title: Edit Topics
    redirect: rainlab/forum/topics
    redirectClose: rainlab/forum/topics

# Preview page
preview:
    title: Preview Topics