# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: babybellyfitness.forum::lang.channels.name

# Model Form Field configuration
form: ~/plugins/babybellyfitness/forum/models/channel/fields.yaml

# Model Class name
modelClass: BabyBellyFitness\Forum\Models\Channel

# Default redirect location
defaultRedirect: babybellyfitness/forum/channels

# Create page
create:
    title: babybellyfitness.forum::lang.channels.create
    redirect: babybellyfitness/forum/channels/update/:id
    redirectClose: babybellyfitness/forum/channels

# Update page
update:
    title: babybellyfitness.forum::lang.channels.update
    redirect: babybellyfitness/forum/channels
    redirectClose: babybellyfitness/forum/channels

# Preview page
preview:
    title: babybellyfitness.forum::lang.channels.preview