# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Channels

# Attribute name
nameFrom: title

# Model Class name
modelClass: BabyBellyFitness\Forum\Models\Channel

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
